### PR TITLE
Add textContents of target elements as :desc into metadata

### PR DESCRIPTION
**Pull request by drobune**
Enable to post select elements with their text contents.

### CODE REVIEW

**Comment by drobune** [comment]
Serverside has fixed. demo
[Gyazo](https://gyazo.com/ddf6ac0b13493798c14b13873517a26e)

**Comment by uiureo** [comment]
what if the text context is too large? it might be rejected because of the validation of the server.

**Comment by drobune** [comment]
When text context is too large, gyazo servers will return HTTP-status 413, same as Image is too large.
Bcuz the servers limits http request body size.

**Comment by rakusai** [comment]
Too many white space and blank lines:

[Gyazo](https://gyazo.com/cf7b2ffac8bbfeda64ab396de7f9da0a)

those text should be trimmed in good format.

**Comment by drobune** [comment]
>Too many white space and blank lines:

ok, fixed!

before
[Gyazo](https://nota.gyazo.com/e15489c012979f3bd715ee9daab29b66)

after
[Gyazo](https://nota.gyazo.com/3ba7eac0b3ba9579c5e51ffdef29c910)

**Comment by drobune** [comment]
fix bugs
[Gyazo](https://nota.gyazo.com/477e66ce99830eedd8ba66fc29c742ad)

**Comment by akiroom** [comment]
LGTM...!

**Comment by pastak** [comment]
LGTM!

**Comment by nna774** [comment]
I want this feature very much!!

**Comment by pastak** [comment]
I'll ready to release on next Tuesday :rocket:

**Comment by drobune** [comment]
[Gyazo](https://gyazo.com/343dc86c9a981e5a9f39189b8b253593)

**Pull request merged**
