### PR TITLE
New ui

### PR DESCRIPTION
**Pull request by pastak**
- Show menu in current window instead of popup.
- You can select default behavior by option setting

[Gyazo](http://gyazo.com/ed5137e87051ce3a01ce08fc4742fc94)

### CODE REVIEW

**Comment by pastak** [comment]
# TODO

- [ ] Cursor image on Select Element
- [ ] Change layer color on Select Element ( blue )

**Comment by pastak** [comment]
現状

[Gyazo](https://gyazo.com/97996a3145d005e0463cd347f086e3fb)

**Comment by uiureo** [comment]
:+1:

**Comment by pastak** [comment]
@uiureo @rakusai please review it :bow:

**Comment by rakusai** [comment]
I've tested the new UI.
I think we can make it better.

problem
- the shadow does not look modern and cool.
- the label text (English) is not good.

**Comment by rakusai** [comment]
seems bug:

- sometimes, it will start element capturing mode without the showing the menu.

**Comment by pastak** [comment]
OK, I'll remove shadow of box. I wanna improve English text so I want to
help to it.

I cant reproduce this bug. Please tell me its detail.

**Pull request merged**
