### PR TITLE
Renewal toolbar and popup message

### PR DESCRIPTION
**Pull request by pastak**
ref: #158 #159 

Toolbar

[Gyazo](https://gyazo.com/af466d2ce479dcefc58f7e390c73eda3)

PopUp Message

[Gyazo](https://gyazo.com/208388930fa0ba666768fbac36ef3973)

### CODE REVIEW

**Comment by pastak** [comment]
@rakusai @yoshiharatakeru please review it

**Comment by rakusai** [comment]
we want to show only domain name not full URL because URL is sometime super long and not beautiful.

**Comment by rakusai** [comment]
can we add split line between Whole Page and My Images? 
like this:
`Whole Page | My Images`

**Comment by pastak** [comment]
show only domain name.

[Gyazo](https://gyazo.com/3d4cb6ea395cf5c7809ce8f88d4f0bd4)

**Comment by pastak** [comment]
added split line 

[Gyazo](https://gyazo.com/48c138cc3b741067269c6b09d549469d)

**Comment by pastak** [comment]
@rakusai I updated

**Comment by pastak** [comment]
[Gyazo](https://gyazo.com/4fba009fed8f32de001b16e32f1385eb)

**Comment by pastak** [comment]
[Gyazo](https://gyazo.com/7c2f8559fb8afffbc2d336c05e530b56)

**Pull request merged**
